### ISSUE TITLE
Reduce computation time of control loop

### ISSUE THREAD

**Issue by andreadelprete** [loco-3d/torque-control#2]
At the moment the control loop on HRP-2 runs at 400 Hz, whereas we would like to reach 1 kHz especially in order to improve velocity estimation through finite differences. Most of the time is taking by these three parts:

1. about 0.7 ms: flexibility observer (see [sot-state-observation](https://github.com/amifsud/sot-state-observation)
2. about 0.6 ms: QP for inverse dynamics using eiquadprog (see [invdyn](https://github.com/stack-of-tasks/invdyn))
3. about 0.5 ms: low-level sensor reading and motor commands

We believe that for all these three pieces of code there is room for improving performance, so that we could increase the control frequency.

**Comment by andreadelprete** [comment]
We did some measurements and found out that about half of the computation time of the flexibility observer is taken by sot-dynamics, which computes the input signals of the observer. This means that when we'll shift to the new version of sot-dynamics (sot v3), which is based on pinocchio, this time will be automatically reduced! @amifsud @proyan @jcarpent @thomasfla

**Comment by andreadelprete** [comment]
An issue dedicated to reducing the computation time of the flexibility estimator has been opened here: https://github.com/Loco3D/sensing/issues/1

**Comment by andreadelprete** [comment]
Another issue dedicated to reducing the computation time of the controller QP has been opened here: https://github.com/stack-of-tasks/invdyn/issues/2

**Comment by andreadelprete** [comment]
Just as a quick update:
1. To reduce the computation time of the estimation @thomasfla is developing a new simple base estimator
2. I spent some time to optimize the QP solver used in the inverse dynamics controller, which led to a 15% reduction of the computation time
3. @thomasfla has different ideas about how to optimize the time to access the sensors on the robot, but at the moment we have no one taking care of this

**Comment by thomasfla** [comment]
Switching to simple estimator and using some optimization in the IOs access allows us to work at a control cycle of 1.5ms.
